CREATE DATABASE PROYECTO;
USE PROYECTO;

CREATE TABLE OPERADOR (
	RUN VARCHAR(10) UNIQUE PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR (50) NOT NULL,
    APELLIDO VARCHAR (50) NOT NULL,
    DIRECCION VARCHAR (100) NOT NULL,
    CORREO_ELECTRONICO VARCHAR(100) NOT NULL
);
CREATE TABLE USUARIO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (50) NOT NULL,
    APELLIDO VARCHAR (50) NOT NULL,
    CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR (100)
);

CREATE TABLE CAPACITACION (
	CODIGO_CURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (50) NOT NULL,
    HORARIO VARCHAR (100) NOT NULL
);

/* CREATE USER 'admintienda'@'localhost' IDENTIFIED BY 'admintienda';
GRANT ALL PRIVILEGES ON Telovendo.* TO 'admintienda'@'localhost';*/
-- OPERADOR
INSERT INTO OPERADOR (RUN, NOMBRE, APELLIDO, DIRECCION, CORREO_ELECTRONICO) 
VALUES ('23345678-9', 'Ricardo', 'Pérez González', '1990-05-15', 'ricardo@gmail.com');
INSERT INTO OPERADOR (RUN, NOMBRE, APELLIDO, DIRECCION, CORREO_ELECTRONICO) 
VALUES ('18458206-6', 'Mauricio', 'Morales Veas', '1994-03-17', 'mauro@gmail.com');
INSERT INTO OPERADOR (RUN, NOMBRE, APELLIDO, DIRECCION, CORREO_ELECTRONICO) 
VALUES ('9876543-9', 'Jose', 'González Pérez', '1997-07-22', 'jose@gmail.com');
INSERT INTO OPERADOR (RUN, NOMBRE, APELLIDO, DIRECCION, CORREO_ELECTRONICO) 
VALUES ('1234567-2', 'Pablo', 'Pérez Pereira', '1991-02-15', 'pablo@gmail.com');
INSERT INTO OPERADOR (RUN, NOMBRE, APELLIDO, DIRECCION, CORREO_ELECTRONICO)  
VALUES ('22345678-1', 'Karem', 'Ortiz Vergara', '1993-05-27', 'karem@gmail.com');
INSERT INTO OPERADOR (RUN, NOMBRE, APELLIDO, DIRECCION, CORREO_ELECTRONICO) 
VALUES ('8765432-1', 'Jason', 'Kruger González', '1960-05-22', 'jason@gmail.com');
INSERT INTO OPERADOR (RUN, NOMBRE, APELLIDO, DIRECCION, CORREO_ELECTRONICO) 
VALUES ('7654321-9', 'Ignacia', 'Pérez González', '1977-02-10', 'ignacia@gmail.com');
INSERT INTO OPERADOR (RUN, NOMBRE, APELLIDO, DIRECCION, CORREO_ELECTRONICO) 
VALUES ('16543789-0', 'Lala', 'Lolo Guerra', '1988-12-11', 'lala@gmail.com');
INSERT INTO OPERADOR (RUN, NOMBRE, APELLIDO, DIRECCION, CORREO_ELECTRONICO) 
VALUES ('1234567-9', 'Camila', 'Vergara Plaza', '1977-09-10', 'camila@gmail.com');
INSERT INTO OPERADOR (RUN, NOMBRE, APELLIDO, DIRECCION, CORREO_ELECTRONICO) 
VALUES ('22345678-9', 'Juan', 'González Pérez', '1999-05-19', 'juan@gmail.com');
-- USUARIO
INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO_ELECTRONICO, TELEFONO) 
VALUES ('Rodrigo', 'Pérez González', 'rperezg@gmail.com', '+56998765432');
INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO_ELECTRONICO, TELEFONO) 
VALUES ('Ignacio', 'Morales Veas', 'imoralesv@gmail.com', '+56912765432');
INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO_ELECTRONICO, TELEFONO)  
VALUES ('Luis', 'González Pérez', 'lgonzalezp@gmail.com', '+56998435432');
INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO_ELECTRONICO, TELEFONO)  
VALUES ('Pedro', 'Pérez Pereira', 'pperezp@gmail.com', '+56996565432');
INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO_ELECTRONICO, TELEFONO) 
VALUES ('Karola', 'Ortiz Vergara', 'kortizv@gmail.com', '+56998765432');
INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO_ELECTRONICO, TELEFONO) 
VALUES ('Jackson', 'Pérez González', 'jperezg@gmail.com', '+56238765432');
INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO_ELECTRONICO, TELEFONO) 
VALUES ('Francisca', 'González González', 'fgonzalezg@gmail.com', '+56998645432');
INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO_ELECTRONICO, TELEFONO) 
VALUES ('Alvara', 'Flores Guerra', 'afloresg@gmail.com', '+56999875432');
INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO_ELECTRONICO, TELEFONO) 
VALUES ('Camilo', 'Plaza Plaza', 'cplazap@gmail.com', '+56998743232');
INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO_ELECTRONICO, TELEFONO) 
VALUES ('Ricardo', 'Plaza Pérez', 'rplazap@gmail.com', '+56998760932');

-- CAPACITACION

INSERT INTO CAPACITACION (CODIGO_CURSO, NOMBRE, HORARIO) VALUES (001, 'CAPACITACION_01', '11:00 AM');
INSERT INTO CAPACITACION (CODIGO_CURSO, NOMBRE, HORARIO) VALUES (002, 'CAPACITACION_02', '12:00 AM');
INSERT INTO CAPACITACION (CODIGO_CURSO, NOMBRE, HORARIO) VALUES (003, 'CAPACITACION_03', '13:00 PM');
INSERT INTO CAPACITACION (CODIGO_CURSO, NOMBRE, HORARIO) VALUES (004, 'CAPACITACION_04', '14:00 PM');
INSERT INTO CAPACITACION (CODIGO_CURSO, NOMBRE, HORARIO) VALUES (005, 'CAPACITACION_05', '15:00 PM');
INSERT INTO CAPACITACION (CODIGO_CURSO, NOMBRE, HORARIO) VALUES (006, 'CAPACITACION_06', '16:00 PM');
INSERT INTO CAPACITACION (CODIGO_CURSO, NOMBRE, HORARIO) VALUES (007, 'CAPACITACION_07', '17:00 PM');
INSERT INTO CAPACITACION (CODIGO_CURSO, NOMBRE, HORARIO) VALUES (008, 'CAPACITACION_08', '18:00 PM');
INSERT INTO CAPACITACION (CODIGO_CURSO, NOMBRE, HORARIO) VALUES (009, 'CAPACITACION_09', '08:00 AM');
INSERT INTO CAPACITACION (CODIGO_CURSO, NOMBRE, HORARIO) VALUES (010, 'CAPACITACION_10', '09:00 AM');
INSERT INTO CAPACITACION (CODIGO_CURSO, NOMBRE, HORARIO) VALUES (011, 'CAPACITACION_11', '10:00 AM');

SELECT * FROM CAPACITACION;
SELECT * FROM OPERADOR;
SELECT * FROM USUARIO;
